[build]
  command = "ng build"
  commandOrigin: config
  publish: /opt/build/repo/dist/PMS
   publishOrigin: config
  functions = "netlify/functions"
  functionsDirectory: /opt/build/repo/netlify/functions
 
  [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200


